stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "safahamad/simple-web" 

build_image:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
  only:
    - master 

push_image:
  stage: deploy
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $IMAGE_NAME
  only:
    - master 
  environment:
    name: production
    url: http://your-production-url.com
  dependencies:
    - build_image
