name: Node.js CI

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16  # Change this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
    
    - name: Build and Push Docker Image
      run: docker build -t myimage

    - name: Log in to Docher Hub
      run: docker login -u ${{ secrets.myusername }} -p ${{ secrets.mypassword }}

    - name: Tag Docker Image
      run: docker tag myimage ${{ secrets.myusername }}/myimage:latest

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.myusername }}/myimage:latest  
